<a href="https://colab.research.google.com/github/Rupesh-Kataria/Data-Science-By-CodeBasics/blob/main/Pandas_3(Different_ways_of_creating_Dataframe).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Different Ways of Creating Dataframe 
To know more about them go to pandas io which consist of API to read and write

In [2]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/pandas/3_different_ways_of_creating_dataframe/weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [3]:
df=pd.read_excel("weather_data.xlsx","Sheet1")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [4]:
weather_data = {                                   #in the above dictionary method
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [5]:
weather_data = [                         #this is a tuple of rows 
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
#Note while creating dataframe using tuple you need to give the name of column
df=pd.DataFrame(weather_data,columns=["day","temperature","windspeed","event"])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [6]:
weather_data = [          #dictionary inside list
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow